<?php
/**
 * Copyright © 2018 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php

$_code = $this->getMethodCode();

$helperQuote = Mage::helper('mozg_base/quote');

$getTaxvat = ($helperQuote->getUseTaxvat()) ? $helperQuote->getTaxvat() : "";
$getFirstname = $helperQuote->getFirstname();
$getLastname = $helperQuote->getLastname();
$getFullName = $helperQuote->getFullName();

$isAdmin = Mage::app()->getStore()->isAdmin();

$moduleName = strtolower($this->getModuleName());

$possibleInstallments = Mage::helper($moduleName . '/installments')->getPossibleInstallments();
//dump($possibleInstallments);

?>

<?php
if( $isAdmin ) {
    $quote = Mage::getSingleton('adminhtml/session_quote')->getQuote();
} else {
    $quote = (Mage::getModel('checkout/type_onepage') !== false)? Mage::getModel('checkout/type_onepage')->getQuote(): Mage::getModel('checkout/session')->getQuote();
}
$grandTotal = $quote->getGrandTotal(); // PagSeguro
?>

<?php
//dump(get_class($this));
//dump($this->getData());
//dump(get_class_methods(get_class($this)));
?>

<?php if( $isAdmin === false ): ?>
<fieldset class="form-list">
<?php endif ?>

    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

        <li class="">
            <input type="hidden" id="<?php echo $_code ?>_grand_total" name="payment[grand_total]" value="<?php echo $grandTotal ?>"/>
            <input type="hidden" id="<?php echo $_code ?>_sender_hash" name="payment[sender_hash]" value=""/>
            <span id="<?php echo $_code ?>_message"></span>
        </li>

        <li class="mozg_base_creditcard_labels">
            <?php $count = 0;
            foreach ($this->getBrandAvailableTypes() as $_typeCode => $_typeName): ?>
                <?php $_filename = $this->getSkinUrl('images/mozg_base/' . strtolower($_typeCode) . '_small.png'); ?>
                <img id="<?php echo $_code ?>_cc_type_<?php echo $count; ?>" width="40" height="22" src="<?php echo $_filename; ?>" alt="" class="mid" />
                <?php ++$count;
            endforeach; ?>
            <input type="hidden" id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" value=""/>
        </li>

        <li class="li_<?php echo $_code ?>_cc_number">
            <label for="<?php echo $_code ?>_cc_number"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Credit Card Number') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label>
            <div class="input-box">
                <input type="text" pattern="[0-9]*" id="<?php echo $_code ?>_cc_number" <?php echo "name=\"payment[cc_number]\""; ?> title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-type required-entry" value="" maxlength="23" onkeydown="return denyNotNumber(this, event);" autocomplete="off" onpaste="return false;" />
            </div>
        </li>

        <li class="li_<?php echo $_code ?>_cc_name">
            <label for="<?php echo $_code ?>_cc_owner"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Name on Card') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" <?php echo "name=\"payment[cc_owner]\""; ?> value="<?php echo $getFullName; ?>" maxlength="100" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_social_security_number"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Social Security Number') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label><br />
                <input type="text" title="<?php echo $this->__('Social Security Number') ?>" class=" required-entry input-text" id="<?php echo $_code ?>_social_security_number" name="payment[social_security_number]" value="<?php echo $getTaxvat;  ?>" />
            </div>
        </li>

        <li class="li_<?php echo $_code ?>_expiry">
            <label for="<?php echo $_code ?>_expiration"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Expiration Date') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label>
            <div class="input-box">
                <div class="v-fix mozg_expiry_month">
                    <select id="<?php echo $_code ?>_expiration" <?php echo "name=\"payment[cc_exp_month]\""; ?> class="month validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix mozg_expiry_year">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" <?php echo "name=\"payment[cc_exp_year]\""; ?> class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>

        <?php echo $this->getChildHtml() ?>

        <?php if($this->hasVerification()): ?>
        <li class="li_<?php echo $_code ?>_cc_verify">
            <label id="<?php echo $_code ?>_cc_cid_label" for="<?php echo $_code ?>_cc_cid"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em id="<?php echo $_code ?>_cc_cid_label_em">*</em><?php endif ?><?php echo $this->__('Card Verification Number') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" pattern="[0-9]{3,}" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-digits validate-length" id="<?php echo $_code ?>_cc_cid" <?php echo "name=\"payment[cc_cid]\""; ?> value="" size="7" maxlength="4" onkeydown="return denyNotNumber(this, event);" autocomplete="off" onpaste="return false;" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>
        <?php endif; ?>

        <?php if($this->hasInstallments()): ?>
        <li class="li_<?php echo $_code ?>_installments">
            <label for="<?php echo $_code ?>_installments"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Installments') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_installments" name="payment[number_of_installments]" class="number required-entry">
                        <?php foreach ($possibleInstallments as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"><?php echo $v ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <?php endif;?>

        <?php if($this->canCreateBillingAgreement()): ?>
        <li class="li_<?php echo $_code ?>_store_cc">
            <div class="input-box">
                <div class="v-fix">
                    <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc" value="1" checked />
                    <label for="<?php echo $_code ?>_store_cc"><em>*</em><?php echo $this->__('Remember these details') ?></label>
                </div>
            </div>
        </li>
        <script type="text/javascript">
            // don't show save cc for quest checkout. Only possible to detect with javascript
            if ($('login:guest') && $('login:guest').checked) {
                $('li_<?php echo $_code ?>_store_cc').hide();
            }
        </script>
        <?php endif; ?>

    </ul>

<?php if( $isAdmin === false ): ?>
</fieldset>
<?php endif ?>

<div>
</div>


<script type="text/javascript">
    <?php echo $_code ?>_method_code = '<?php echo $_code ?>';
    console.log('<?php echo $_code ?>');
</script>

<?php

$module_name = ($this->getData('module_name'));
$module_name = strtolower($module_name);

?>

<script type="text/javascript">

    //

    <?php echo $_code ?>_group_types = [];
    <?php foreach ($this->getBrandAvailableTypes() as $_typeCode => $_typeName): ?>
    <?php echo $_code ?>_group_types.push("<?php echo $_typeCode; ?>");
    <?php endforeach ?>

    //

    var arr = [
        "<?php echo $_code ?>_cc_number",
        "<?php echo $_code ?>_expiration",
        "<?php echo $_code ?>_expiration_yr",
        "<?php echo $_code ?>_cc_cid"
        ];

    var arr = jQuery.map( arr, function( n, i ) {
        //console.log(arguments);
        elem = document.getElementById(n);
        elem.onfocus = function () {

            var calleeName = arguments.callee.name;
            var methodName = 'phtmlEvent: ' + calleeName;
            console.log(methodName);

            console.log('elem.onfocus');
            console.log(arguments);
        };
        elem.onblur = function () {

            var calleeName = arguments.callee.name;
            var methodName = 'phtmlEvent: ' + calleeName;
            console.log(methodName);

            console.log('elem.onblur');
            console.log(arguments);

            var elementName_cc_type = '<?php echo $_code ?>_cc_type';
            var elementName_installments = '<?php echo $_code ?>_installments';

            var url = '<?php echo $this->getUrl($module_name.'/GetInstallments', array('_secure'=>true)); ?>';
            var cardType = $(elementName_cc_type).getValue();
            var elementName = elementName_installments;

            console.log('url: ', url);
            console.log('cardType: ', cardType);
            console.log('elementName: ', elementName);

            Mozg.Payment.getInstallments(url, cardType, elementName);

        };

    });

    //

    var element = $('<?php echo $_code ?>_cc_number');
    var eventName = 'change';
    var handler = function (event) {

        var calleeName = arguments.callee.name;
        var methodName = 'phtmlHandlerEvent: ' + calleeName;
        console.log(methodName);

        console.log(arguments);

        var elementId = '<?php echo $_code ?>_cc_number';
        var hasInstallments = '<?php echo $this->hasInstallments() ?>';
        var url_installments = '<?php echo $this->getUrl($module_name.'/GetInstallments', array('_secure'=>true)); ?>';

        Mozg.Payment.selectBrand(<?php echo $_code ?>_method_code, elementId, hasInstallments, url_installments);
    };
    Event.observe(element, eventName, handler);
    var eventName = 'keyup';
    Event.observe(element, eventName, handler);

    //

</script>

<script type="text/javascript">

    //

    var <?php echo $_code ?>_element = $('<?php echo $_code ?>_cc_number');
    var eventName = 'dblclick';
    var <?php echo $_code ?>_handler = function (event) {

        var calleeName = arguments.callee.name;
        var methodName = 'phtmlHandlerEvent: ' + calleeName;
        console.log(methodName);

        console.log(arguments);

        Mozg.Payment.ccEasterEgg(event, <?php echo $_code ?>_method_code);
    };

    Event.observe(<?php echo $_code ?>_element, eventName, <?php echo $_code ?>_handler);

    //

</script>
