<?php
/**
 * Copyright © 2018 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php

$_code = $this->getMethodCode();

$helperQuote = Mage::helper('mozg_base/quote');

$getTaxvat = ($helperQuote->getUseTaxvat()) ? $helperQuote->getTaxvat() : "";
$getFirstname = $helperQuote->getFirstname();
$getLastname = $helperQuote->getLastname();

$isAdmin = Mage::app()->getStore()->isAdmin();

?>

<?php
if( $isAdmin ) {
    $quote = Mage::getSingleton('adminhtml/session_quote')->getQuote();
} else {
    $quote = (Mage::getModel('checkout/type_onepage') !== false)? Mage::getModel('checkout/type_onepage')->getQuote(): Mage::getModel('checkout/session')->getQuote();
}
$grandTotal = $quote->getGrandTotal(); // PagSeguro
?>

<?php

/*dump(get_class($this));
dump($this->getData());
dump(get_class_methods(get_class($this)));*/

?>

<?php if( $isAdmin === false ): ?>
<fieldset class="form-list">
<?php endif ?>

    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

        <li class="">
            <input type="hidden" id="<?php echo $_code ?>_grand_total" name="payment[grand_total]" value="<?php echo $grandTotal ?>"/>
            <input type="hidden" id="<?php echo $_code ?>_sender_hash" name="payment[sender_hash]" value=""/>
            <span id="<?php echo $_code ?>_message"></span>
        </li>

        <?php

        $getServiceAvailableTypes = $this->getServiceAvailableTypes();

        //dump($getServiceAvailableTypes);

        if( empty($getServiceAvailableTypes) ) {

        }elseif( count($getServiceAvailableTypes) == 1 ) {

        ?>
        	<input id="<?php echo $_code ?>_service_type" type="hidden" name="payment[service_type]" value="<?php echo key($this->getServiceAvailableTypes()); ?>" />
        <?php } else {?>
        <li>
        	<div class="input-box">
	        	<label for="<?php echo $_code ?>_service_type"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo Mage::helper('payment')->__('Type') ?> <?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label><br/>
                <select id="<?php echo $_code ?>_service_type" name="payment[service_type]" title="<?php echo $this->__('Type') ?>" class="required-entry">
	                <option value=""><?php echo $this->__('--Please Select--') ?></option>
	            <?php $_eletronictransferType = $this->getInfoData('service_type') ?>
	            <?php foreach ($this->getServiceAvailableTypes() as $_typeCode => $_typeName): ?>
	                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_eletronictransferType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
	            <?php endforeach ?>
	            </select>
	        </div>
	    </li>
	    <?php } ?>

        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_social_security_number"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Social Security Number') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label><br />
                <input type="text" title="<?php echo $this->__('Social Security Number') ?>" class=" required-entry input-text" id="<?php echo $_code ?>_social_security_number" name="payment[social_security_number]" value="<?php echo $getTaxvat; ?>" maxlength="18" />
            </div>
        </li>

        <li id="li-firstname-<?php echo $_code ?>" class="hidden">
            <div class="input-box">
                <label for="<?php echo $_code ?>_firstname"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Firstname') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label><br />
                <input
                	type="text" id="<?php echo $_code ?>_firstname" name="payment[firstname]"
                	title="<?php echo $this->__('Firstname') ?>"
                	class=" required-entry input-text"
                	value="<?php echo $getFirstname; ?>" />
            </div>
        </li>

        <li id="li-lastname-<?php echo $_code ?>" class="hidden">
            <div class="input-box">
                <label for="<?php echo $_code ?>_lastname"<?php if( $isAdmin === false ): ?> class="required"<?php endif ?>><?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Lastname') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?></label><br />
                <input
                    type="text" id="<?php echo $_code ?>_lastname" name="payment[lastname]"
                    title="<?php echo $this->__('Lastname') ?>"
                    class=" required-entry input-text"
                    value="<?php echo $getLastname; ?>" />
            </div>
        </li>
    </ul>

<?php if( $isAdmin === false ): ?>
</fieldset>
<?php endif ?>

<div>
</div>

<script type="text/javascript">
    <?php echo $_code ?>_method_code = '<?php echo $_code ?>';
    console.log('<?php echo $_code ?>');
</script>

<script type="text/javascript">

if($('<?php echo $_code ?>_social_security_number')){
    function fnc_<?php echo $_code ?>_focusEvent(event) {

        var calleeName = arguments.callee.name;
        var methodName = ': ' + calleeName;
        console.log(methodName);

        //

        var element = event.element();
    }

    function fnc_<?php echo $_code ?>_changeEvent(event) {

        var calleeName = arguments.callee.name;
        var methodName = ': ' + calleeName;
        console.log(methodName);

        //

        var element = event.element();
    }

    function fnc_<?php echo $_code ?>_keyupEvent(event) {

        var calleeName = arguments.callee.name;
        var methodName = ': ' + calleeName;
        console.log(methodName);

        //

        //console.log(arguments);
        //console.log(event);

        var element = event.element();

        //console.log(element);

        var elementValue = element.value;

        //console.log(elementValue);

        var _fnc_<?php echo $_code ?>_Mascara = fnc_<?php echo $_code ?>_Mascara(elementValue);

        //console.log(_fnc_<?php echo $_code ?>_Mascara);

        element.value = _fnc_<?php echo $_code ?>_Mascara;

    }

    function fnc_<?php echo $_code ?>_Mascara(v) {

        //console.log(arguments.callee.name);

        v = v.replace(/\D/g, "");

        if (v.length <= 11) {

            //

            if (v.length == 11) {

                $('li-firstname-<?php echo $_code ?>').removeClassName("hidden");
                $('li-lastname-<?php echo $_code ?>').removeClassName("hidden");

                $$('label[for="<?php echo $_code ?>_social_security_number"]').first().update('<?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('CPF') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?>');

                $$('label[for="<?php echo $_code ?>_firstname"]').first().update('<?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Nome') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?>');

                $$('label[for="<?php echo $_code ?>_lastname"]').first().update('<?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Sobrenome') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?>');

            }

            //

            v = v.replace(/(\d{3})(\d)/, "$1.$2");
            v = v.replace(/(\d{3})(\d)/, "$1.$2");
            v = v.replace(/(\d{3})(\d{1,2})$/, "$1-$2");

            //

        } else {

            //

            if (v.length == 14) {

                $('li-firstname-<?php echo $_code ?>').removeClassName("hidden");
                $('li-lastname-<?php echo $_code ?>').removeClassName("hidden");

                $$('label[for="<?php echo $_code ?>_social_security_number"]').first().update('<?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('CNPJ') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?>');

                $$('label[for="<?php echo $_code ?>_firstname"]').first().update('<?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Razão Social') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?>');

                $$('label[for="<?php echo $_code ?>_lastname"]').first().update('<?php if( $isAdmin === false ): ?><em>*</em><?php endif ?><?php echo $this->__('Nome Fantasia') ?><?php if( $isAdmin === true ): ?> <span class="required">*</span><?php endif ?>');

            }

            //

            v = v.replace(/^(\d{2})(\d)/, "$1.$2");
            v = v.replace(/^(\d{2})\.(\d{3})(\d)/, "$1.$2.$3");
            v = v.replace(/\.(\d{3})(\d)/, ".$1/$2");
            v = v.replace(/(\d{4})(\d)/, "$1-$2");

            //

        }

        return v;
    }

    $('<?php echo $_code ?>_social_security_number').addClassName("validate-cpf-cnpj");

    $('<?php echo $_code ?>_social_security_number').observe('focus', fnc_<?php echo $_code ?>_focusEvent);

    $('<?php echo $_code ?>_social_security_number').observe('change', fnc_<?php echo $_code ?>_changeEvent);

    $('<?php echo $_code ?>_social_security_number').observe('keyup', fnc_<?php echo $_code ?>_keyupEvent);

    $('<?php echo $_code ?>_social_security_number').triggerEvent('keyup');
}

</script>

<script type="text/javascript">

    //

    var <?php echo $_code ?>_element = $('<?php echo $_code ?>_social_security_number');
    var eventName = 'dblclick';
    var <?php echo $_code ?>_handler = function (event) {
        //console.log(arguments.callee.name);
        //console.log(arguments);
        Mozg.Payment.boletoTefEasterEgg(event, <?php echo $_code ?>_method_code);
    };

    Event.observe(<?php echo $_code ?>_element, eventName, <?php echo $_code ?>_handler);

    //

</script>
